### ISSUE TITLE
param sfo ATTRIBUTE default of 65536 causes issues

### ISSUE THREAD

**Issue by cy33hc** [PacBrew/ps4-openorbis#9]
The param.sfo ATTRIBUTE default of 65536 causes problem. My example was that it cause the ImeDialog to swap the X/O for enter button. Please make ATTRIBUTE set by a param in the add_pkg function. Value was originally "0".

https://github.com/PacBrew/ps4-openorbis/blob/076243317e925c4ac58f1ff6f91c1fdc1aabbab2/vars/ps4.cmake#L156

**Comment by Cpasjuste** [comment]
Thanks !
